root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - google
  - plugin:import/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:import/typescript
  - plugin:vue/vue3-recommended
  - plugin:prettier-vue/recommended
  - prettier
  - eslint-config-prettier
plugins:
  - vue
  - eslint-plugin-tsdoc
  - '@typescript-eslint'
  - vuejs-accessibility
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  createDefaultProgram: true
  project: ./tsconfig.json
rules:
  new-cap: off
  no-invalid-this: off
  no-irregular-whitespace: off
  no-unused-vars: warn
  require-jsdoc: warn
  valid-jsdoc: off
  vue/html-self-closing: [error, html: { void: always }]
  vue/multi-word-component-names: warn
  import/no-named-as-default: off
  import/no-named-as-default-member: off
settings:
  import/resolver:
    typescript: {}
    alias:
      map:
        - ['@', './src']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
        - .vue
